### ISSUE TITLE
AttributeError: 'module' object has no attribute '_TensorLike'

### ISSUE THREAD

**Issue by joekh1** [PacktPublishing/Artificial-Intelligence-for-Robotics#1]
I was trying to compile chapter 4 code, I  got the following error.

compiling CNN network...
Traceback (most recent call last):
  File "trainTheCNN.py", line 127, in <module>
    cnNetwork = LeNet.build(width=128, height=128, depth=3, classes=2)
  File "trainTheCNN.py", line 39, in build
    input_shape=inputShape))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/sequential.py", line 164, in add
    layer(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 279, in assert_input_compatibility
    K.is_keras_tensor(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 470, in is_keras_tensor
    if not is_tensor(x):
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 478, in is_tensor
    return isinstance(x, tf_ops._TensorLike) or tf_ops.is_dense_tensor_like(x)
AttributeError: 'module' object has no attribute '_TensorLike'

But After I upgraded tensorflow, I got the following issue:

Using TensorFlow backend. 
Illegal instruction

can you please help me?
Thank you

**Comment by joekh1** [comment]
I downgraded to tensorflow 1.5 and it works fine now! thank you
